InformationClass.destroy_all

begin

  InformationClass.create!({class_code: "C.2", name: "Services delivery support", description: "Services delivery support functions provide the critical policy, programmatic, and managerial foundation to support Federal government operations. Security objectives and impact levels for service delivery support information and systems are generally determined by the natures of the supported direct services and constituencies being supported. If a system stores, processes, or communicates national security information, it is defined as a national security system, and is outside the scope of this guideline. Service delivery support activities are defined in this section."})
  InformationClass.create!({class_code: "C.3", name: "Government resource management", description: "Resource management functions are the back office support activities that enable the government to operate effectively. Security objectives and impacts for resource management functions are determined by the direct service missions and constituencies ultimately being supported. It is likely that all Federal government information systems store, process, and operate under the control of IT infrastructure maintenance information (e.g., password files and file and network access settings). A basic set of security controls will apply to this information and processes to combat potential corruption, misuse, or abuse of system information and processes."})
  InformationClass.create!({class_code: "D", name: "Mission-based", description: "In general, individual agencies should identify the mission information types processed by their systems. This Appendix identifies some information types that might be processed by Federal government organizations. The material includes mission information and potential impacts of unauthorized disclosure, modification, or unavailability of mission information.

  The primary purpose for Federal government information systems is to support provision of basic services to U.S. citizens and residents. This section addresses information types associated with both services provided by the Federal government to citizens and mechanisms used to achieve the purposes of government or deliver services for citizens. Delivery mechanisms include financial vehicles, direct government delivery, and indirect government delivery. Federal government missions or delivery mechanisms distributed among 26 mission areas and modes of delivery are identified in Table D-1. Each mission area and delivery mode corresponds to a Services to Citizens or Mode of Delivery business area as defined in the BRM described in the FEA Consolidated Reference Model Document Version 2.3. There is not a one- to-one mapping of services and delivery modes to government departments and agencies. Some departments and agencies focus on a single mission. Others support multiple missions within a mission area. Still others provide services associated with several different mission areas.

  An information type is associated with each Federal government mission and delivery mode. The identity of each information type is defined by the mission with which it is associated. Some of the management and support functions executed to support delivery of services or manage government resources are also executed by some agencies in delivering services to citizens. (See especially the 'General Government' functions in Section C.2.8. of Appendix C) Most of these information types could be included in Appendix D as mission-based information types. Because the BRM categorizes them as services delivery support functions, they are included in Volume I, Section 4.1.2 and Appendix C and are not repeated in Appendix D.

  The common impact determination factors described in Volume I, Section 4.2.3 and 4.4, also apply to mission-based information."})

rescue Exception => e
    puts "Exception: #{e}"
end

puts "Created #{InformationClass.count} Information Classes."