InformationGroup.destroy_all

begin

  information_class = InformationClass.find_by(class_code: "C.2").id

  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.1", name: "Controls and oversight", description: "Controls and Oversight information is used to ensure that the operations and programs of the Federal government and its external business partners comply with applicable laws and regulations and prevent waste, fraud, and abuse."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.2", name: "Regulatory development", description: "Regulatory Development involves activities associated with providing input to the lawmaking process in developing regulations, policies, and guidance to implement laws."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.3", name: "Planning and budgeting", description: "Planning and Budgeting involves the activities of determining strategic direction, identifying and establishing programs and processes to enable change, and allocating resources (capital and labor) among those programs and processes."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.4", name: "Internal risk management and mitigation", description: "Internal risk management and mitigation involves all activities relating to the processes of analyzing exposure to risk and determining appropriate counter-measures. Note that risks to information and information systems associated with internal risk management and mitigation activities may inherently affect the resistance to compromise/damage and recovery from damage with respect to a broad range of critical infrastructures and key national assets."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.5", name: "Revenue collection", description: "Revenue Collection includes the collection of Government income from all sources. Note: Tax collection is accounted for under the Taxation Management information type in the General Government mission area."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.6", name: "Public affairs", description: "Public Affairs activities involve the exchange of information and communication between the Federal Government, citizens and stakeholders in direct support of citizen services, public policy, and/or national interest."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.7", name: "Legislative relations", description: "Legislative Relations involves activities aimed at the development, tracking, and amendment of public laws through the legislative branch of the Federal Government."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.2.8", name: "General government", description: "General Government involves the overhead costs of the Federal Government, including legislative and executive activities; provision of central fiscal, personnel, and property activities; and the provision of services that cannot reasonably be classified in any other service support area. As a normal rule, all activities reasonably or closely associated with other service support areas or information types shall be included in those service support areas or information types rather than listed as a part of general government. This service support area is reserved for central government management operations; most service delivery (mission-based) management activities would not be included here. Unlike the other service support functions, some general government information types are associated with specific organizations (e.g., Department of the Treasury, Executive Office of the President, Internal Revenue Service)."})

  information_class = InformationClass.find_by(class_code: "C.3").id

  InformationGroup.create!({information_class_id: information_class, group_code: "C.3.1", name: "Administrative management", description: "Administrative Management involves the day-to-day management and maintenance of the internal infrastructure. Administrative information is usually routine and is relatively low impact. However, some administrative management information is either very sensitive (e.g., logistics management for nuclear or other hazardous materials, security management information, and security clearance management information) or critical (e.g., inventory control and logistics management information needed to support time-critical operations). National security information is outside the scope of this guideline. [See Appendix A, Glossary of Terms, for a definition of national security information/systems.] Routine administrative management information systems that do not process classified information are not usually designated national security systems, even if they are critical to the direct fulfillment of military or intelligence missions."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.3.2", name: "Financial management", description: "Financial management involves the aggregate set of accounting practices and procedures that allow for the accurate and effective handling of all government revenues, funding, and expenditures. Confidentiality impacts associated with financial management information are generally associated with the sensitivity of the existence of specific projects, programs, and/or technologies that might be revealed by unauthorized disclosure of information. For integrity, temporary successful frauds can affect agency image, and corrective actions are often disruptive to agency operations. Permanent loss/unavailability of financial management information can cripple agency operations."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.3.3", name: "Human resource management", description: "Human resource management activities involve all activities associated with the recruitment and management of personnel."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.3.4", name: "Supply chain management", description: "Supply chain management involves the purchasing, tracking, and overall management of goods and services."})
  InformationGroup.create!({information_class_id: information_class, group_code: "C.3.5", name: "Information and technology management", description: "IT management involves the coordination of IT resources and systems required to support or enable a citizen service. Impacts to information associated with the operation of IT systems generally need to be considered even when all mission-related information processed by the system is intended to be available to the general public. The relevant issues may be different for integrity and availability than for confidentiality. Information that has been made public, by definition, requires no confidentiality protection. In contrast, integrity and availability protection cannot be maintained for copies of information that have been distributed to the public. Integrity and availability assurance can only be maintained by maintaining copies of information in organization-controlled information systems."})

  information_class = InformationClass.find_by(class_code: "D").id

  InformationGroup.create!({information_class_id: information_class, group_code: "D.1", name: "Defense and national security", description: "Defense and national security operations protect and advance U.S. National Security interests and, if deterrence fails, decisively defeat threats to those interests. Defense and national security activities include military operations, border protection, and intelligence gathering. Defense operations are subdivided into the following sub-elements:

  - Strategic National and Theater Defense - Establishing national and multinational military objectives, sequencing initiatives, defining limits and assessing risks for the use of military and other instruments of national power, developing global plans or theater war plans to achieve these objectives, and providing military forces and other capabilities in accordance with strategic plans;
  - Operational Defense - Linking tactics and strategy by establishing operational objectives needed to accomplish the strategic objectives, sequencing events to achieve the operational objectives, initiating actions, and applying resources to bring about and sustain these events; and
  - Tactical Defense - The ordered arrangement and maneuver of combat elements in relation to each other and to the enemy to achieve combat objectives.

  Impacts to information and many information systems associated with defense and national security missions may affect the security of a broad range of critical infrastructures and key national assets. Systems that, involve command and control of military forces, weapons control29, involve equipment that is an integral part of a weapon or weapons system, are critical to the direct fulfillment of military missions or are otherwise employed in strictly military operations30 are defined under Public Law as national security systems. National security information and national security systems are outside the scope of this guideline. Information assurance responsibilities are delegated to the Department of Defense for systems that are operated by the Department of Defense, or another entity on behalf of the Department of Defense31. Security objectives and impact levels associated with these systems are determined by the Department of Defense."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.2", name: "Homeland security", description: "Homeland Security involves protecting the nation against terrorist attacks. This includes analyzing threats and intelligence, guarding borders and airports, protecting critical infrastructure, and coordinating the response emergencies. The Homeland Security Line of Business is defined by the President's Strategy on Homeland Security. Note: Some of the Critical Mission Areas from the President's strategy are included in other information classes and categories."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.3", name: "Intelligence operations", description: "Intelligence operations involve the development and management of accurate, comprehensive, and timely foreign intelligence on national security topics. Information systems, the function, operation, or use of, which involve intelligence activities or are critical to the direct fulfillment of intelligence missions are defined under Public Law as national security systems. National security information and national security systems are outside the scope of this guideline. Security objectives and impact levels associated with national security systems are determined by the head of each agency exercising control of the system."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.4", name: "Disaster management", description: "Disaster management involves the activities required to prepare for, mitigate, respond to, and repair the effects of all physical and humanitarian disasters whether natural or man-made. Compromise of much information associated with any of the missions within the disaster management mission area may seriously impact the security of a broad range of critical infrastructures and key national assets."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.5", name: "International affairs and commerce", description: "International Affairs and Commerce involves the non-military activities that promote U.S. policies and interests beyond our national borders, including the negotiation of conflict resolution, treaties, and agreements. In addition, this function includes: foreign economic development and social/political development; diplomatic relations with other Nations; humanitarian, technical and other developmental assistance to key Nations; and global trade. Information that is protected by procedures established and authorized under criteria specified in an Executive Order or an Act of Congress to be kept classified in the interests of foreign policy are national security related35. Security objectives and impact levels associated with such national security information are determined by the head of each agency exercising control of the system and are outside the scope of this guideline."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.6", name: "Natural resources", description: "The Natural Resources mission area includes all activities involved in conservation planning, land management, and national park/monument tourism that affect the nation's natural and recreational resources, both private and federal. Note: Energy-related natural resources are covered in the Energy Management mission area."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.7", name: "Energy", description: "Energy refers to all actions performed by the government to ensure the procurement and management of energy resources, including the production, sale and distribution of energy, as well as the management of spent fuel resources. Energy management includes all types of mass- produced energy (e.g., hydroelectric, nuclear, wind, solar, or fossil fuels). Also included in this mission area is the oversight of private industry."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.8", name: "Environmental management", description: "Environmental management includes all functions required to determine proper environmental standards and ensure their compliance."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.9", name: "Economic development", description: "Economic Development includes the activities required to promote commercial/industrial development and to regulate the American financial industry to protect investors. It also includes the management and control of the domestic economy and the money supply, and the protection of intellectual property and innovation. Note: The promotion of U.S. business overseas is captured in the function, \"International Affairs and Commerce.\""})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.10", name: "Community and social services", description: "Community and Social Services includes all activities aimed at creating, expanding, or improving community and social development, social relationships, and social services in the United States. This includes all activities aimed at locality-specific or nationwide social development and general social services and general community development and social services programs, as well as earned and unearned benefit programs that promote these objectives."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.11", name: "Transportation", description: "Transportation involves all federally supported activities related to the safe passage, conveyance, or transportation of goods and/or people. Note that impacts to some information and many information systems associated with transportation activities may affect the security of, not only the transportation infrastructure, but also to a broad range of other critical infrastructures and key national assets."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.12", name: "Education", description: "Education refers to those activities that impart knowledge or understanding of a particular subject to the public. Education can take place at a formal school, college, university or other training program. This mission area includes all government programs that promote the education of the public, including both earned and unearned benefit programs."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.13", name: "Workforce management", description: "Workforce Management includes those activities that promote the welfare and effectiveness of the Nation's workforce by improving their proficiency, working conditions, advancing opportunities for profitable employment, and strengthening free collective bargaining."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.14", name: "Health", description: "Public Health involves Federal programs and activities charged with ensuring and providing for the health and well being of the public. This includes the direct provision of health care services and immunizations as well as the monitoring and tracking of public health indicators for the detection of trends and identification of widespread illnesses/diseases. It also includes both earned and unearned health care benefit programs. Note that impacts to some public health information and information systems may affect the security of critical elements of the public health infrastructure."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.15", name: "Income security", description: "Income Security includes activities designed to ensure that members of the public are provided with the necessary means - both financial and otherwise - to sustain an adequate level of existence. This includes all benefit programs, both earned and unearned, that promote these goals for members of the public."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.16", name: "Law enforcement", description: "Law enforcement involves the protection of people, places, and things from criminal activity resulting from non-compliance with U.S. laws. This includes patrols, undercover operations, response to emergency calls, as well as arrests, raids, and seizures of property. Impacts to some information and information systems associated with law enforcement missions may affect the security of a broad range of critical infrastructures and key national assets. Some information associated with Federal law enforcement is categorized as national security information. Rules governing establishment of impact levels and controls associated with national security information are governed by a separate set of policies and are outside the scope of this guideline. Confidentiality and integrity impacts are often determined by statutory and regulatory requirements that vary by violation."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.17", name: "Litigation and judicial services", description: "Litigation and judicial activities involve all activities necessary for the development and oversight of Federal programs."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.18", name: "Federal correctional activities", description: "Correctional Activities involves all Federal activities that ensure the effective incarceration and rehabilitation of convicted criminals."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.19", name: "General sciences and innovation", description: "General Science and Innovation includes all Federal activities to meet the national need to advance knowledge in this area. This includes general research and technology programs, space exploration activities, and other research and technology programs that have diverse goals and cannot be readily classified into another mission area or information type."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.20", name: "Knowledge creation and management", description: "Knowledge Creation and Management involves the programs and activities in which the Federal Government creates or develops a body or set of knowledge, the manipulation and analysis of which can provide inherent benefits for both the Federal and private sector."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.21", name: "Regulatory compliance and enforcement", description: "Regulatory Compliance and Enforcement involves the direct monitoring and oversight of a specific individual, group, industry, or community participating in a regulated activity via market mechanisms, command and control features, or other means to control or govern conduct or behavior."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.22", name: "Public goods creation and management", description: "The construction, manufacturing, administration, and/or management of goods, structures, facilities, common resources, etc. used for the general well being of the American public or society at large."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.23", name: "Federal financial assistance", description: "Federal Financial Assistance is the provision of earned and unearned financial or monetary-like benefits to individuals, groups, or corporations."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.24", name: "Credit and insurance", description: "Credit and Insurance involves the use of government funds to cover the subsidy cost of a direct loan or loan guarantee or to protect/indemnify members of the public from financial losses."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.25", name: "Transfers to state/local governments", description: "Transfers to States and Local Governments involve the transfer of funds or financial assistance from the Federal government to State and Local governments and Indian tribes."})
  InformationGroup.create!({information_class_id: information_class, group_code: "D.26", name: "Direct services for citizens", description: "Direct Services for Citizens refers to the delivery of a good or service to (or on behalf of) the citizenry by the federal government with no other intervening persons, conditions, or organizations."})

rescue Exception => e
  puts "Exception: #{e}"
end

puts "Created #{InformationGroup.count} Information Groups."