load '~/Code/typist/db/seeds/0_impact_level_seeds.rb'
load '~/Code/typist/db/seeds/1_security_objective_seeds.rb'
load '~/Code/typist/db/seeds/2_information_class_seeds.rb'
load '~/Code/typist/db/seeds/3_information_group_seeds.rb'
load '~/Code/typist/db/seeds/4_information_type_seeds.rb'